<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-DED1LDD" failures="0" tests="9" name="com.a2j.tests.RpTest" time="18.877" errors="1" timestamp="2020-06-10T13:28:10 IST" skipped="5">
  <testcase classname="com.a2j.tests.RpTest" name="loginTest" time="0.481">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.a2j.pages.LoginPage.login3(LoginPage.java:121)
at com.a2j.tests.RpTest.loginTest(RpTest.java:77)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- loginTest -->
  <system-out/>
  <testcase classname="com.a2j.tests.RpTest" name="verifyloginpasswordTextBox1" time="3.908"/>
  <system-out/>
  <testcase classname="com.a2j.tests.RpTest" name="caserequests" time="0.000">
    <skipped/>
  </testcase> <!-- caserequests -->
  <system-out/>
  <testcase classname="com.a2j.tests.RpTest" name="loginbutton" time="9.450"/>
  <system-out/>
  <testcase classname="com.a2j.tests.RpTest" name="verifyloginuserTextBox" time="5.038"/>
  <system-out/>
  <testcase classname="com.a2j.tests.RpTest" name="caseid" time="0.000">
    <skipped/>
  </testcase> <!-- caseid -->
  <system-out/>
  <testcase classname="com.a2j.tests.RpTest" name="accept" time="0.000">
    <skipped/>
  </testcase> <!-- accept -->
  <system-out/>
  <testcase classname="com.a2j.tests.RpTest" name="downlaoadfrom2" time="0.000">
    <skipped/>
  </testcase> <!-- downlaoadfrom2 -->
  <system-out/>
  <testcase classname="com.a2j.tests.RpTest" name="teardown" time="0.000">
    <skipped/>
  </testcase> <!-- teardown -->
  <system-out/>
</testsuite> <!-- com.a2j.tests.RpTest -->
